# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quickScan',
            fields=[
                ('scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_uuid', models.CharField(max_length=40)),
                ('scan_date', models.DateTimeField(editable=False)),
                ('scan_url', models.URLField()),
                ('scan_status', models.CharField(max_length=7)),
                ('scan_results', models.TextField(default='', max_length=5000)),
            ],
        ),
    ]
